import React, { useState } from "react";
import { ExternalLink, Download, Loader2, CheckCircle2 } from "lucide-react";
import { exportResults, getDownloadUrl } from "../services/api";

interface ExportButtonProps {
  jobId: string;
}

const downloadReportAsTxt = async (jobId: string) => {
  const response = await fetch(getDownloadUrl(jobId));
  const jsonData = await response.json();

  const lines: string[] = [];

  const now = new Date();
  const dateStr = now.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-IN", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const divider  = "?".repeat(60);
  const thinLine = "-".repeat(60);

  lines.push(divider);
  lines.push("  DECISION MINDS  |  EXECUTIVE MEETING REPORT");
  lines.push(divider);
  lines.push(`  Date      : ${dateStr}`);
  lines.push(`  Time      : ${timeStr}`);
  lines.push(`  Report ID : ${jobId.slice(0, 8).toUpperCase()}`);
  lines.push(`  Status    : AI Verified`);
  lines.push(divider);
  lines.push("");

  lines.push("  SECTION 1 - EXECUTIVE SUMMARY");
  lines.push(thinLine);
  lines.push("");
  if (jsonData?.meeting_summary) {
    const words = jsonData.meeting_summary.trim().split(/\\s+/);
    let curr = "  ";
    words.forEach((word: string) => {
      if ((curr + word).length > 60) {
        lines.push(curr.trimEnd());
        curr = "  " + word + " ";
      } else {
        curr += word + " ";
      }
    });
    if (curr.trim()) lines.push(curr.trimEnd());
  } else {
    lines.push("  No summary available.");
  }
  lines.push("");
  lines.push(divider);
  lines.push("");

  const items = jsonData?.action_items || [];
  lines.push(`  SECTION 2 - KEY DECISIONS & ACTION ITEMS  [${items.length}]`);
  lines.push(thinLine);
  lines.push("");

  if (items.length > 0) {
    const high   = items.filter((i: any) => i.priority?.toLowerCase() === "high");
    const medium = items.filter((i: any) => i.priority?.toLowerCase() === "medium");
    const low    = items.filter((i: any) => i.priority?.toLowerCase() === "low");

    const renderItems = (group: any[], label: string) => {
      if (group.length === 0) return;
      lines.push(`  >> ${label}`);
      lines.push("");
      group.forEach((item: any, i: number) => {
        const owner    = item.owner && item.owner.toLowerCase() !== "unknown"
                           ? item.owner : "To Be Assigned";
        const deadline = item.deadline || "Not Specified";
        lines.push(`  ${i + 1}. ${item.task || "N/A"}`);
        lines.push(`     Owner    : ${owner}`);
        lines.push(`     Deadline : ${deadline}`);
        lines.push("");
      });
    };

    renderItems(high,   "HIGH PRIORITY");
    renderItems(medium, "MEDIUM PRIORITY");
    renderItems(low,    "LOW PRIORITY");
  } else {
    lines.push("  No action items identified.");
    lines.push("");
  }

  lines.push(divider);
  lines.push("");

  const participants = jsonData?.participants || [];
  if (participants.length > 0) {
    lines.push("  SECTION 3 - ATTENDEES");
    lines.push(thinLine);
    lines.push("");
    participants.forEach((p: any, i: number) => {
      lines.push(`  ${i + 1}. ${p.name || "Unknown"}`);
    });
    lines.push("");
  }

  const nextSection = participants.length > 0 ? "4" : "3";
  lines.push(`  SECTION ${nextSection} - NEXT STEPS`);
  lines.push(thinLine);
  lines.push("");

  if (items.length > 0) {
    lines.push("  Based on this meeting, the following are immediate");
    lines.push("  priorities for the team:");
    lines.push("");
    items.slice(0, 3).forEach((item: any, i: number) => {
      const deadline = item.deadline || "at the earliest";
      lines.push(`  ${i + 1}. ${item.task}`);
      lines.push(`     ? Complete ${deadline}`);
      lines.push("");
    });
  } else {
    lines.push("  No immediate next steps identified.");
    lines.push("");
  }

  lines.push(divider);
  lines.push("");

  lines.push("  CONFIDENTIAL");
  lines.push(thinLine);
  lines.push("  This report is intended solely for the addressee(s).");
  lines.push("  It contains confidential information generated by");
  lines.push("  Decision Minds AI. Unauthorized use or distribution");
  lines.push("  is strictly prohibited.");
  lines.push("");
  lines.push(divider);
  lines.push("");

  lines.push("  Powered by Decision Minds");
  lines.push("  Better Decisions. Better Lives.");
  lines.push(`  www.decisionminds.com  |  Report ID: ${jobId.slice(0, 8).toUpperCase()}`);
  lines.push(divider);

  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `executive_report_${jobId.slice(0, 8)}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const ExportButton: React.FC<ExportButtonProps> = ({ jobId }) => {
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const handleExport = async (target: "local_log" | "sharepoint_document") => {
    setLoading(true);
    try {
      if (target === "local_log") {
        await downloadReportAsTxt(jobId);
        const a = document.createElement("a");
        a.href = getDownloadUrl(jobId);
        a.download = `action_items_${jobId.slice(0, 8)}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      } else {
        await exportResults(jobId, target);
      }
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    } catch (e) {
      console.error("Export failed", e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex gap-3">
      <button
        onClick={() => handleExport("local_log")}
        disabled={loading}
        className="flex-1 py-3.5 px-4 border-2 border-[#F26A21] text-[#F26A21] hover:bg-[#F26A21] hover:text-white rounded-full transition-all duration-200 flex items-center justify-center gap-2 text-sm font-semibold disabled:opacity-50"
      >
        {loading ? (
          <Loader2 size={14} className="animate-spin" />
        ) : done ? (
          <CheckCircle2 size={14} />
        ) : (
          <Download size={14} />
        )}
        {done ? "Downloaded!" : "Download Report"}
      </button>
      <button
        onClick={() => handleExport("sharepoint_document")}
        disabled={loading}
        className="flex-1 py-3.5 px-4 bg-[#0a5791] hover:bg-[#E55D1B] text-white rounded-full transition-all duration-200 flex items-center justify-center gap-2 text-sm font-semibold shadow-button disabled:opacity-50"
      >
        <ExternalLink size={14} />
        Export to SharePoint
      </button>
    </div>
  );
};

export default ExportButton;
